#!/usr/bin/env python
import argparse, sys, heapq, models
#import pdb
from collections import namedtuple

parser = argparse.ArgumentParser(description='Simple phrase based decoder.')
parser.add_argument('-i', '--input', dest='input', default='data/input', help='File containing sentences to translate (default=data/input)')
parser.add_argument('-t', '--translation-model', dest='tm', default='data/tm', help='File containing translation model (default=data/tm)')
parser.add_argument('-s', '--stack-size', dest='s', default=1, type=int, help='Maximum stack size (default=1)')
parser.add_argument('-n', '--num_sentences', dest='num_sents', default=sys.maxint, type=int, help='Number of sentences to decode (default=no limit)')
parser.add_argument('-l', '--language-model', dest='lm', default='data/lm', help='File containing ARPA-format language model (default=data/lm)')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False,  help='Verbose mode (default=off)')
opts = parser.parse_args()

tm = models.TM(opts.tm, sys.maxint)
lm = models.LM(opts.lm)
sys.stderr.write('Decoding %s...\n' % (opts.input,))
input_sents = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]
#pdb.set_trace()
#hypothesis = namedtuple('hypothesis', 'logprob, lm_state, predecessor, phrase')
hypothesis = namedtuple('hypothesis', 'logprob, translated_logprob, lm_state, predecessor, phrase, translated')
for f in input_sents:
    # The following code implements a DP monotone decoding
    # algorithm (one that doesn't permute the target phrases).
    # Hence all hypotheses in stacks[i] represent translations of 
    # the first i words of the input sentence.
    # HINT: Generalize this so that stacks[i] contains translations
    # of any i words (remember to keep track of which words those
    # are, and to estimate future costs)
    initial_hypothesis = hypothesis(0.0, 0.0, lm.begin(), None, None, [])

    stacks = [{} for _ in f] + [{}]
    #stacks[0][lm.begin()] = initial_hypothesis
    stacks[0][""] = initial_hypothesis
    for i, stack in enumerate(stacks[:-1]):
        # extend the top s hypotheses in the current stack
        for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.logprob): # prune, default max only
            for j in xrange(i+1,len(f)+1): # search from i-th translated word to end
                if f[i:j] in tm: # is a pharse
                    for phrase in tm[f[i:j]]: # find all possible phrase translation
                        # select insertion point
                        for k in range(len(h.translated)+1):
                            # words to translate  translated - inserted phrase - translated
                            toTranslate = h.translated[:k] + [phrase.english.split()] + h.translated[k:]
                            #toTranslate = [phrase.english.split()] 
                            
                            # TM log-prob
                            logprob =  h.translated_logprob + phrase.logprob
                            translated_logprob = logprob
                            # LM log-prob
                            lm_state = lm.begin()
                            temp = [x for y in toTranslate for x in y]
                            for word in temp:
                                (lm_state, word_logprob) = lm.score(lm_state, word)
                                logprob += word_logprob
                            
                            logprob += lm.end(lm_state) #if j == len(f) else 0.0
                            
                            # reordering score
                            # to add
                            
                            new_hypothesis = hypothesis(logprob, translated_logprob, lm_state, h, phrase, toTranslate)
                            sent = " ".join([x for y in toTranslate for x in y])
                            if sent not in stacks[j] or stacks[j][sent].logprob < logprob:
                                stacks[j][sent] = new_hypothesis
                            #if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob: # second case is recombination
                            #    stacks[j][lm_state] = new_hypothesis 


    # find best translation by looking at the best scoring hypothesis
    # on the last stack
    winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
    def extract_english_recursive(h):
        #return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
        return " ".join([x for y in h.translated for x in y])
    print extract_english_recursive(winner)

    if opts.verbose:
        def extract_tm_logprob(h):
            return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
        tm_logprob = extract_tm_logprob(winner)
        sys.stderr.write('LM = %f, TM = %f, Total = %f\n' % 
            (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
